### ISSUE TITLE
findById always find the result[0] in history.repository.

### ISSUE THREAD

**Issue by wayahead** [koliberr136a1/loopback-history-extension#1]
In findById of history.repository, {id: id} is missing so that findById always returns result[0] without id matching.

detailes in code: 

       const result = await this.findHistory(
            Boolean(maxDate),
            {
                ...filter,
                where: {
                    and: [filter && filter.where, endDateCondition]
                }
            },
            options
        );

should be :

       const result = await this.findHistory(
            Boolean(maxDate),
            {
                ...filter,
                where: {
                    and: [{id: id}, filter && filter.where, endDateCondition]
                }
            },
            options
        );

**Comment by ckoliber** [comment]
Thanks

bug fixed on #2
